DIDN exact recon - New PR
kevinmicha/DIDN pull request #2
Opened 2021-06-28 09:53 UTC by kevinmicha

Now done from `dev` branch instead of `master`.

2021-06-28 10:03 UTC, zaccharieramzi requested changes
Same as on the other PR

2021-06-28 10:03 UTC, zaccharieramzi commented on gray_model.py
>          out = torch.add(out, residual)
Here watch out for the residual

2021-06-28 10:03 UTC, zaccharieramzi commented on gray_model.py
> +            out = torch.subtract(residual, noise_std * out)
```suggestion
            out = residual - noise_std * out
```

2021-07-16 08:42 UTC, kevinmicha commented on gray_model.py
> +            out = torch.subtract(residual, noise_std * out)
done

2021-07-16 08:43 UTC, kevinmicha commented on gray_model.py
>          out = torch.add(out, residual)
fixed

2021-07-16 09:21 UTC, zaccharieramzi approved these changes
LGTM

2021-07-16 09:23 UTC, kevinmicha commented
Merging

2021-07-16 09:23 UTC, merged